//! Integration tests: parse WDB files and compare against pre-converted FST files.
//!
//! For each corpus test case the repository contains a matching `.fst` file
//! generated by `wdbcvt`. These tests recursively verify:
//!  - Scope names, types, child counts, and variable counts match the FST.
//!  - Variable names, widths, and (spot-checked) last values match the FST.

use std::collections::{BTreeMap, HashMap};
use std::fs::File;
use std::io::BufReader;
use std::path::{Path, PathBuf};

use fst_reader::{
    FstFilter, FstHierarchyEntry, FstReader, FstScopeType, FstSignalValue, FstVarType,
};
use wdb_parser::{ScopeKind, ScopeRef, VarDefKind, WdbFile};

/// Concrete WdbFile type used throughout these tests.
type WdbFileOnDisk = WdbFile<BufReader<File>>;

// ---------------------------------------------------------------------------
// FST tree
// ---------------------------------------------------------------------------

#[derive(Debug)]
struct FstScope {
    name: String,
    tpe: FstScopeType,
    vars: Vec<FstVar>,
    children: Vec<FstScope>,
}

#[derive(Debug)]
struct FstVar {
    name: String,
    tpe: FstVarType,
    length: u32,
    handle_index: u32,
}

/// Read the FST file and return it as a tree rooted at a synthetic top node.
fn read_fst_tree(fst_path: &Path) -> FstScope {
    let f = std::fs::File::open(fst_path).expect("open FST");
    let mut reader = FstReader::open(BufReader::new(f)).expect("parse FST");

    // Stack of scopes being built; starts with a synthetic root.
    let mut stack: Vec<FstScope> = vec![FstScope {
        name: "__root__".into(),
        tpe: FstScopeType::Module,
        vars: vec![],
        children: vec![],
    }];

    reader
        .read_hierarchy(|entry| {
            match entry {
                FstHierarchyEntry::Scope { name, tpe, .. } => {
                    stack.push(FstScope {
                        name: name.clone(),
                        tpe,
                        vars: vec![],
                        children: vec![],
                    });
                }
                FstHierarchyEntry::UpScope => {
                    let finished = stack.pop().expect("UpScope with empty stack");
                    stack.last_mut().unwrap().children.push(finished);
                }
                FstHierarchyEntry::Var {
                    name,
                    tpe,
                    length,
                    handle,
                    is_alias,
                    ..
                } => {
                    if !is_alias {
                        stack.last_mut().unwrap().vars.push(FstVar {
                            name: name.clone(),
                            tpe,
                            length,
                            handle_index: handle.get_index() as u32,
                        });
                    }
                }
                _ => {}
            }
        })
        .expect("read FST hierarchy");

    assert_eq!(stack.len(), 1, "unbalanced Scope/UpScope in FST");
    stack.pop().unwrap()
}

/// Collect value changes from an FST for all handles in the tree.
fn collect_all_fst_changes(
    fst_path: &Path,
    root: &FstScope,
) -> HashMap<u32, BTreeMap<u64, String>> {
    use fst_reader::FstSignalHandle;

    fn collect_handles(scope: &FstScope, out: &mut Vec<u32>) {
        for v in &scope.vars {
            out.push(v.handle_index);
        }
        for c in &scope.children {
            collect_handles(c, out);
        }
    }

    let mut all_handles = Vec::new();
    collect_handles(root, &mut all_handles);

    let f = std::fs::File::open(fst_path).expect("open FST");
    let mut reader =
        FstReader::open_and_read_time_table(BufReader::new(f)).expect("parse FST time table");

    let handles: Vec<FstSignalHandle> = all_handles
        .iter()
        .map(|&i| FstSignalHandle::from_index(i as usize))
        .collect();
    let filter = FstFilter::filter_signals(handles);
    let mut out: HashMap<u32, BTreeMap<u64, String>> = HashMap::new();

    reader
        .read_signals(&filter, |time, handle, value| {
            let s = match value {
                FstSignalValue::String(bytes) => String::from_utf8_lossy(bytes).into_owned(),
                FstSignalValue::Real(r) => format!("{}", r),
            };
            out.entry(handle.get_index() as u32)
                .or_default()
                .insert(time, s);
            Ok::<(), ()>(())
        })
        .expect("read FST signals");

    out
}

// ---------------------------------------------------------------------------
// Scope / var type classification (for loose matching)
// ---------------------------------------------------------------------------

/// Broad category used for type comparisons, so minor naming differences don't fail.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ScopeCategory {
    Module,
    Process,
    Function,
    Task,
    Block,
    Generate,
    Package,
    Other,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum VarCategory {
    Logic,   // wire, reg, logic, wor, supply, etc.
    Integer, // integer, natural, parameter (numeric)
    Real,
    Other,
}

fn fst_var_category(t: FstVarType) -> VarCategory {
    match t {
        FstVarType::Wire
        | FstVarType::Reg
        | FstVarType::Tri
        | FstVarType::TriAnd
        | FstVarType::TriOr
        | FstVarType::TriReg
        | FstVarType::Tri0
        | FstVarType::Tri1
        | FstVarType::Wand
        | FstVarType::Wor
        | FstVarType::Supply0
        | FstVarType::Supply1
        | FstVarType::Port
        | FstVarType::Bit
        | FstVarType::Logic => VarCategory::Logic,
        FstVarType::Integer
        | FstVarType::Time
        | FstVarType::Int
        | FstVarType::ShortInt
        | FstVarType::LongInt
        | FstVarType::Byte
        | FstVarType::Enum
        | FstVarType::Parameter => VarCategory::Integer,
        FstVarType::Real
        | FstVarType::RealParameter
        | FstVarType::RealTime
        | FstVarType::ShortReal => VarCategory::Real,
        // fst-reader 0.17 does not have VHDL-specific var types; those
        // signals appear as Wire/Reg/Port. Map them to Other so they don't
        // cause false mismatches.
        _ => VarCategory::Other,
    }
}

fn wdb_var_category(k: VarDefKind) -> VarCategory {
    use wdb_parser::VarDefKind::*;
    match k {
        VerilogNet
        | VerilogNetWand
        | VerilogNetWor
        | VerilogNetTri
        | VerilogNetTriand
        | VerilogNetTrior
        | VerilogNetTri0
        | VerilogNetTri1
        | VerilogNetTrireg
        | VerilogNetSupply0
        | VerilogNetSupply1
        | VerilogVar => VarCategory::Logic,
        VerilogParameter => VarCategory::Other,  // wdbcvt emits params as Wire in FST
        // VHDL types: fst-reader 0.17 doesn't emit VHDL-specific var types,
        // so we can't distinguish them from Logic in the FST. Map to Other
        // to avoid false mismatches.
        VhdlSignal | VhdlSignalParam | VhdlVariable | VhdlGeneric | VhdlConstant
        | VhdlSubprogramParam => VarCategory::Other,
        Unknown(_) => VarCategory::Other,
    }
}

fn fst_scope_category(t: FstScopeType) -> ScopeCategory {
    match t {
        FstScopeType::Module => ScopeCategory::Module,
        FstScopeType::Task => ScopeCategory::Task,
        FstScopeType::Function | FstScopeType::VhdlFunction => ScopeCategory::Function,
        FstScopeType::Begin | FstScopeType::Fork | FstScopeType::VhdlBlock => {
            ScopeCategory::Block
        }
        FstScopeType::Generate
        | FstScopeType::VhdlForGenerate
        | FstScopeType::VhdlIfGenerate
        | FstScopeType::VhdlGenerate => ScopeCategory::Generate,
        FstScopeType::Package | FstScopeType::VhdlPackage => ScopeCategory::Package,
        FstScopeType::VhdlArchitecture => ScopeCategory::Module,
        FstScopeType::VhdlProcess | FstScopeType::VhdlProcedure => ScopeCategory::Process,
        _ => ScopeCategory::Other,
    }
}

fn wdb_scope_category(k: ScopeKind) -> ScopeCategory {
    match k {
        ScopeKind::VerilogModule
        | ScopeKind::SvInterface
        | ScopeKind::SvModport
        | ScopeKind::VhdlEntity => {
            ScopeCategory::Module
        }
        ScopeKind::VerilogTask => ScopeCategory::Task,
        ScopeKind::VerilogFunction => ScopeCategory::Other,  // wdbcvt emits Verilog functions as Module
        ScopeKind::VhdlFunction => ScopeCategory::Function,
        // NamedBlock maps to Other: wdbcvt sometimes emits these as Module, sometimes
        // Begin.  Don't enforce a category so we don't get false mismatches.
        ScopeKind::NamedBlock => ScopeCategory::Other,
        ScopeKind::VerilogProcess | ScopeKind::VhdlProcess | ScopeKind::VhdlProcedure => {
            ScopeCategory::Other  // wdbcvt emits processes as Module in FST
        }
        ScopeKind::VhdlGenerate | ScopeKind::VhdlGenerateOrBlock => ScopeCategory::Generate,
        ScopeKind::VhdlPackage | ScopeKind::SvPackage => ScopeCategory::Package,
        ScopeKind::Root | ScopeKind::Unknown(_) => ScopeCategory::Other,
    }
}


// ---------------------------------------------------------------------------
// WDB value formatting (for comparison with FST strings)
// ---------------------------------------------------------------------------

/// Walk the type table to find the enum literal table for a type, following
/// `Alias` and single-element-type `Array` chains.
///
/// Returns `None` if the type ultimately resolves to something other than an
/// enumeration (e.g. `Integer`, `Real`, `Record`).
fn resolve_to_enum_literals(type_idx: usize, wdb: &WdbFileOnDisk) -> Option<&[String]> {
    let te = wdb.hierarchy().type_entry(type_idx)?;
    match &te.kind {
        wdb_parser::TypeKind::Enumeration { literals, .. } => Some(literals.as_slice()),
        wdb_parser::TypeKind::Alias { target_index, .. } => {
            resolve_to_enum_literals(*target_index as usize, wdb)
        }
        wdb_parser::TypeKind::Array { element_type_index, .. } => {
            resolve_to_enum_literals(*element_type_index as usize, wdb)
        }
        _ => None,
    }
}

/// Convert a raw WDB value record to a lowercase logic string comparable to
/// the binary strings produced by FST / wdbcvt.
///
/// Returns `None` when the type is not a logic-like type (e.g. integer,
/// real, or an unrecognised encoding).
fn wdb_to_logic_string(raw: &[u8], var: &wdb_parser::VarInfo, wdb: &WdbFileOnDisk) -> Option<String> {
    if var.is_vhdl() {
        // VHDL enum scalars and arrays (std_ulogic, std_logic_vector, …):
        // each byte is an enum index; map it to the literal character.
        let literals = resolve_to_enum_literals(var.type_index as usize, wdb)?;
        let mut s = String::with_capacity(raw.len());
        for &b in raw {
            let lit = literals.get(b as usize)?;
            // Enum literals for std_ulogic look like "'0'"; strip the quotes.
            let ch = lit.trim_matches('\'').to_lowercase();
            s.push_str(&ch);
        }
        Some(s)
    } else {
        // Verilog / SV: val/xz binary-pair encoding.
        // Derive the parent signal's bit width from the raw record length so
        // that slice-offset extraction works correctly for ports bound to a
        // wider signal.
        let parent_bits = (raw.len() / 8 * 32) as u32;
        let decoded = wdb_parser::decode_verilog_value(raw, parent_bits);
        match decoded {
            wdb_parser::DecodedValue::Logic(bits) => {
                // If the variable is a port bound to a slice of a wider signal,
                // extract only its bit range.
                let start = var.slice_offset as usize;
                let end = start + var.value_size as usize;
                let slice = &bits[start.min(bits.len())..end.min(bits.len())];
                if slice.is_empty() {
                    return None;
                }
                // slice[0] is LSB; reverse to produce MSB-first string.
                Some(slice.iter().rev().map(|b| b.to_char()).collect())
            }
            _ => None,
        }
    }
}

/// Returns true when a signal's raw value is split into multiple on-disk
/// chunks (≥ 275 bytes for VHDL; on-disk record size ≥ 275 for Verilog).
///
/// Chunked signals have their data spread across several `signal_changes`
/// entries keyed by different local signal IDs; reassembly is not yet
/// implemented, so value comparison is skipped for them.
fn is_chunked(var: &wdb_parser::VarInfo) -> bool {
    if var.is_vhdl() {
        var.value_size >= 275
    } else {
        // Verilog on-disk record size = ceil(bit_width / 32) * 8 bytes.
        let record_bytes = ((var.value_size as u64 + 31) / 32) * 8;
        record_bytes >= 275
    }
}

fn format_wdb_value(raw: &[u8], var_info: &wdb_parser::VarInfo, wdb: &WdbFileOnDisk) -> String {
    if var_info.is_vhdl() {
        if let Some(te) = wdb.hierarchy().type_entry(var_info.type_index as usize) {
            if let wdb_parser::TypeKind::Enumeration { literals, .. } = &te.kind {
                if raw.len() == 1 {
                    let idx = raw[0] as usize;
                    if idx < literals.len() {
                        return literals[idx].clone();
                    }
                }
            }
        }
        if var_info.value_size == 4 && raw.len() == 4 {
            let v = i32::from_le_bytes(raw[0..4].try_into().unwrap());
            return format!("{}", v);
        }
        raw.iter().map(|b| format!("{:02x}", b)).collect()
    } else {
        let decoded = wdb_parser::decode_verilog_value(raw, var_info.value_size);
        match decoded {
            wdb_parser::DecodedValue::Logic(bits) => {
                if bits.len() == 1 {
                    bits[0].to_char().to_string()
                } else {
                    bits.iter().rev().map(|b| b.to_char()).collect()
                }
            }
            wdb_parser::DecodedValue::Real(f) => format!("{}", f),
            wdb_parser::DecodedValue::Binary(b) => {
                b.iter().map(|x| format!("{:02x}", x)).collect()
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Recursive hierarchy comparison
// ---------------------------------------------------------------------------

#[derive(Debug)]
struct Mismatch {
    path: String,
    detail: String,
}

impl Mismatch {
    fn new(path: &str, detail: impl Into<String>) -> Self {
        Mismatch { path: path.into(), detail: detail.into() }
    }
}

struct CompareCtx<'a> {
    wdb: &'a WdbFileOnDisk,
    fst_changes: &'a HashMap<u32, BTreeMap<u64, String>>,
    mismatches: Vec<Mismatch>,
}

impl<'a> CompareCtx<'a> {
    fn compare_scope(
        &mut self,
        wdb_sr: ScopeRef,
        fst_scope: &FstScope,
        path: &str,
    ) {
        let hier = self.wdb.hierarchy();
        let wdb_info = hier.scope(wdb_sr);

        // 1a. Name
        if wdb_info.name != fst_scope.name {
            self.mismatches.push(Mismatch::new(
                path,
                format!(
                    "scope name mismatch: WDB={:?} FST={:?}",
                    wdb_info.name, fst_scope.name
                ),
            ));
        }

        // 1b. Type (broad category only)
        let wdb_cat = wdb_scope_category(wdb_info.kind);
        let fst_cat = fst_scope_category(fst_scope.tpe);
        if wdb_cat != fst_cat
            && wdb_cat != ScopeCategory::Other
            && fst_cat != ScopeCategory::Other
        {
            self.mismatches.push(Mismatch::new(
                path,
                format!(
                    "scope type mismatch: WDB={:?} ({:?}) FST={:?} ({:?})",
                    wdb_info.kind, wdb_cat, fst_scope.tpe, fst_cat
                ),
            ));
        }

        // 1c+d. Variables — compare names, widths, values
        self.compare_vars(wdb_sr, fst_scope, path);

        // 1c+d. Child scopes — compare recursively
        self.compare_children(wdb_sr, fst_scope, path);
    }

    fn compare_vars(
        &mut self,
        wdb_sr: ScopeRef,
        fst_scope: &FstScope,
        path: &str,
    ) {
        let hier = self.wdb.hierarchy();
        let wdb_var_refs = hier.scope_vars(wdb_sr);

        // Build name → FstVar map for this scope.
        let fst_var_map: HashMap<&str, &FstVar> =
            fst_scope.vars.iter().map(|v| (v.name.as_str(), v)).collect();

        let fst_count = fst_scope.vars.len();

        let mut fst_unmatched_names: Vec<&str> = fst_scope
            .vars
            .iter()
            .map(|v| v.name.as_str())
            .collect();

        for &vr in wdb_var_refs {
            let v = hier.var(vr);
            let var_path = format!("{}.{}", path, v.name);

            match fst_var_map.get(v.name.as_str()) {
                None => {
                    // Not found as a direct FST variable.  Two legitimate reasons:
                    // (a) The FST expands array/record vars as child scopes (e.g.
                    //     `ipv4_address` in WDB → scope `ipv4_address` in FST).
                    // (b) The FST expands elements as dotted var names (e.g.
                    //     `arr.0`, `arr.1`).
                    // (c) Constants/generics the FST skipped entirely.
                    // Only report if none of those apply.
                    let name_dot = format!("{}.", v.name);
                    let has_var_expansion = fst_scope
                        .vars
                        .iter()
                        .any(|fv| fv.name.starts_with(&name_dot));
                    let has_scope_expansion = fst_scope
                        .children
                        .iter()
                        .any(|c| c.name == v.name);
                    let is_port = !matches!(v.port_mode, wdb_parser::PortMode::NotAPort);
                    if !has_var_expansion && !has_scope_expansion && !is_port && fst_count > 0 {
                        self.mismatches.push(Mismatch::new(
                            &var_path,
                            format!("WDB variable {:?} not found in FST scope {:?}", v.name, path),
                        ));
                    }
                }
                Some(fv) => {
                    // 2a. Name matched.
                    fst_unmatched_names.retain(|&n| n != fv.name.as_str());

                    // 2b. Variable type (broad category).
                    let fst_vcat = fst_var_category(fv.tpe);
                    let wdb_vcat = wdb_var_category(v.kind);
                    if fst_vcat != VarCategory::Other
                        && wdb_vcat != VarCategory::Other
                        && fst_vcat != wdb_vcat
                    {
                        self.mismatches.push(Mismatch::new(
                            &var_path,
                            format!(
                                "var type mismatch: WDB={:?} ({:?}) FST={:?} ({:?})",
                                v.kind, wdb_vcat, fv.tpe, fst_vcat
                            ),
                        ));
                    }

                    // 2c. Width — compare bit/byte widths.
                    // FST length is always in bits. WDB value_size is bits for Verilog
                    // and bytes for VHDL. Normalise both to bits.
                    let wdb_bits = if v.is_vhdl() {
                        v.value_size * 8
                    } else {
                        v.value_size
                    };
                    // Only check width for non-aggregate signals (skip records/arrays
                    // that FST might flatten differently).
                    if fv.length > 0 && wdb_bits > 0 && fv.length != wdb_bits {
                        // Allow the common 1-byte VHDL enum to appear as 1 bit in FST.
                        let is_enum_1bit = v.is_vhdl() && v.value_size == 1 && fv.length == 1;
                        // Allow the case where FST reports the total flattened bit count
                        // while WDB reports only the element size.
                        let is_plausible_multiple =
                            fv.length % wdb_bits == 0 || wdb_bits % fv.length == 0;
                        if !is_enum_1bit && !is_plausible_multiple {
                            self.mismatches.push(Mismatch::new(
                                &var_path,
                                format!(
                                    "width mismatch: WDB={}b FST={}b",
                                    wdb_bits, fv.length
                                ),
                            ));
                        }
                    }

                    // 2d. Value changes: compare at every time point present in
                    // both WDB and FST, for all non-chunked logic-like signals.
                    if v.signal_id.is_some() && !is_chunked(v) {
                        self.compare_all_values(v, fv, &var_path);
                    }
                }
            }
        }
    }

    /// Compare all matching time-point values between WDB and FST for one signal.
    /// Reports up to 3 mismatches per signal to avoid flooding the output.
    fn compare_all_values(
        &mut self,
        var: &wdb_parser::VarInfo,
        fv: &FstVar,
        var_path: &str,
    ) {
        // Use assembled_signal_changes so that wide VHDL signals whose slot range
        // crosses the arena boundary get their overflow bytes included.
        let wdb_changes_owned = match self.wdb.assembled_signal_changes(var) {
            Some(c) if !c.is_empty() => c,
            _ => return,
        };
        let fst_map = match self.fst_changes.get(&fv.handle_index) {
            Some(m) if !m.is_empty() => m,
            _ => return,
        };

        let mut mismatch_count = 0usize;
        // Build time → last_raw from WDB (WDB may emit multiple records per
        // timestamp for uninitialized→initialized transitions; keep the last).
        let mut wdb_last: BTreeMap<u64, Vec<u8>> = BTreeMap::new();
        for (time, raw) in &wdb_changes_owned {
            wdb_last.insert(*time, raw.clone());
        }
        for (time, raw) in &wdb_last {
            if mismatch_count >= 3 {
                break;
            }
            let fst_val = match fst_map.get(time) {
                Some(v) => v,
                None => continue, // no FST change at this exact time (delta cycle etc.)
            };
            let wdb_str = match wdb_to_logic_string(raw, var, self.wdb) {
                Some(s) => s,
                None => continue, // non-logic type — skip
            };
            // FST may prefix binary literals with 'b'; normalise to lowercase.
            let fst_str = fst_val.trim_start_matches('b').to_lowercase();
            if !wdb_str.is_empty() && !fst_str.is_empty() && wdb_str != fst_str {
                self.mismatches.push(Mismatch::new(
                    var_path,
                    format!(
                        "value mismatch at t={}: WDB={:?} FST={:?}",
                        time, wdb_str, fst_str
                    ),
                ));
                mismatch_count += 1;
            }
        }
    }

    fn compare_children(
        &mut self,
        wdb_sr: ScopeRef,
        fst_scope: &FstScope,
        path: &str,
    ) {
        let hier = self.wdb.hierarchy();
        let wdb_children = hier.child_scopes(wdb_sr);

        // Build name → WDB child ScopeRef map.
        let wdb_child_map: HashMap<&str, ScopeRef> = wdb_children
            .iter()
            .map(|&sr| (hier.scope(sr).name.as_str(), sr))
            .collect();

        // Build name → WDB variable map (for detecting aggregate expansions where
        // wdbcvt turns a WDB var into a child scope in the FST).
        let wdb_var_names: std::collections::HashSet<&str> = hier
            .scope_vars(wdb_sr)
            .iter()
            .map(|&vr| hier.var(vr).name.as_str())
            .collect();

        // 1c+d. For each FST child scope, find its WDB counterpart.
        // FST is the ground truth: every FST child must have a WDB match.
        // WDB is allowed to have extra child scopes (library/package scopes wdbcvt omits).
        for fst_child in &fst_scope.children {
            let child_path = format!("{}.{}", path, fst_child.name);
            match wdb_child_map.get(fst_child.name.as_str()) {
                Some(&wdb_child_sr) => {
                    // Matched — recurse.
                    self.compare_scope(wdb_child_sr, fst_child, &child_path);
                }
                None => {
                    // FST has a child scope with no matching WDB scope.
                    // Check if it's an aggregate expansion of a WDB variable
                    // (e.g. VHDL record/array → sub-scope in FST).
                    if !wdb_var_names.contains(fst_child.name.as_str()) {
                        self.mismatches.push(Mismatch::new(
                            &child_path,
                            format!(
                                "FST child scope {:?} not found in WDB scope {:?}",
                                fst_child.name, path
                            ),
                        ));
                    }
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Per-file test logic
// ---------------------------------------------------------------------------

struct TestCase {
    wdb_path: PathBuf,
    fst_path: PathBuf,
    /// Maximum number of hierarchy mismatches tolerated before failing.
    /// Set higher for designs where FST inlines or renames more constructs.
    max_mismatches: usize,
}

impl TestCase {
    fn new(stem: &str) -> Self {
        let base = PathBuf::from("wdb_files/wdbcvt-waveforms/hdl/corpus");
        let dir = base.join(stem);
        TestCase {
            wdb_path: dir.join("sim.wdb"),
            fst_path: dir.join("sim.fst"),
            max_mismatches: 0,
        }
    }

    fn run(&self) {
        assert!(self.wdb_path.exists(), "WDB not found: {:?}", self.wdb_path);
        assert!(self.fst_path.exists(), "FST not found: {:?}", self.fst_path);

        // Parse WDB and load all signal changes.
        let mut wdb = WdbFile::open(&self.wdb_path)
            .unwrap_or_else(|e| panic!("open WDB {:?}: {}", self.wdb_path, e));
        wdb.load_all_signals()
            .unwrap_or_else(|e| panic!("load signals {:?}: {}", self.wdb_path, e));

        // Read FST as a tree.
        let fst_root = read_fst_tree(&self.fst_path);
        if fst_root.children.is_empty() {
            // Nothing in FST to compare against.
            return;
        }

        // Load all FST value changes up-front (one pass).
        let fst_changes = collect_all_fst_changes(&self.fst_path, &fst_root);

        // The WDB root is `_top`; its immediate children correspond to the FST
        // top-level scopes.  We match them by name.
        let hier = wdb.hierarchy();
        let wdb_root = hier.root();
        let wdb_top_children = hier.child_scopes(wdb_root);

        let fst_child_map: HashMap<&str, &FstScope> =
            fst_root.children.iter().map(|s| (s.name.as_str(), s)).collect();

        let mut ctx = CompareCtx {
            wdb: &wdb,
            fst_changes: &fst_changes,
            mismatches: Vec::new(),
        };

        for &top_sr in wdb_top_children {
            let top_info = hier.scope(top_sr);
            match fst_child_map.get(top_info.name.as_str()) {
                Some(fst_top) => {
                    ctx.compare_scope(top_sr, fst_top, &top_info.name);
                }
                None => {
                    // e.g. package scopes that wdbcvt omits from the FST
                }
            }
        }

        if ctx.mismatches.len() > self.max_mismatches {
            let shown = ctx.mismatches.len().min(20);
            let lines: Vec<String> = ctx.mismatches[..shown]
                .iter()
                .map(|m| format!("  [{}] {}", m.path, m.detail))
                .collect();
            panic!(
                "{} hierarchy mismatch(es) (showing first {}) for {:?}:\n{}",
                ctx.mismatches.len(),
                shown,
                self.wdb_path,
                lines.join("\n")
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Corpus tests
// ---------------------------------------------------------------------------

macro_rules! corpus_test {
    ($name:ident, $dir:literal) => {
        #[test]
        fn $name() {
            TestCase::new($dir).run();
        }
    };
    ($name:ident, $dir:literal, max_mismatches = $n:expr) => {
        #[test]
        fn $name() {
            let base = PathBuf::from("wdb_files/wdbcvt-waveforms/hdl/corpus");
            let dir = base.join($dir);
            TestCase {
                wdb_path: dir.join("sim.wdb"),
                fst_path: dir.join("sim.fst"),
                max_mismatches: $n,
            }
            .run();
        }
    };
}

corpus_test!(test_bit_const, "t0_bit_const____");
corpus_test!(test_var_int, "t6_var_int______");
corpus_test!(test_v_wor, "t19_v_wor_______");
corpus_test!(test_phys_user, "t21_phys_user___");
corpus_test!(test_enum_two_id, "t20_enum_two_id_");
// t9: vec1024 — wide array signal; FST may report a different width
corpus_test!(test_vec1024, "t9_vec1024______", max_mismatches = 2);
// Width-coverage tests: validate value change data across signal widths.
//   t10_vec258: 258-byte VHDL std_ulogic_vector — non-chunked, compares all changes.
corpus_test!(test_vec258, "t10_vec258______");
//   t10_vec274: 274-byte VHDL std_ulogic_vector — largest non-chunked size.
corpus_test!(test_vec274, "t10_vec274______");
//   t10_vec275: 275-byte VHDL std_ulogic_vector — smallest chunked size (value skipped).
corpus_test!(test_vec275, "t10_vec275______");
//   t10_vec276: 276-byte VHDL std_ulogic_vector — chunked.
corpus_test!(test_vec276, "t10_vec276______");
// Width-coverage tests: validate value change data across signal widths.
//   t10_vec258: 258-byte VHDL std_ulogic_vector — non-chunked, compares all changes.
corpus_test!(test_vec258, "t10_vec258______");
//   t10_vec274: 274-byte VHDL std_ulogic_vector — largest non-chunked size.
corpus_test!(test_vec274, "t10_vec274______");
//   t10_vec275: 275-byte VHDL std_ulogic_vector — smallest chunked size (value skipped).
corpus_test!(test_vec275, "t10_vec275______");
//   t10_vec276: 276-byte VHDL std_ulogic_vector — chunked.
corpus_test!(test_vec276, "t10_vec276______");
corpus_test!(test_pkg_unused, "t54_pkg_unused__");
corpus_test!(test_con_int, "t52_con_int_____");
corpus_test!(test_inst3_empty, "t53_inst3_empty_");
corpus_test!(test_lib_1164_bit, "t54_lib_1164_bit");
corpus_test!(test_v_port_slc, "t37_v_port_slc__");
corpus_test!(test_sv_sgn8_pos, "t27_sv_sgn8_pos_");

// Contrib — complex VHDL designs with records / flattening differences.
#[test]
fn test_contrib_arp_tb() {
    let base = PathBuf::from("wdb_files/wdbcvt-waveforms/testdata/contrib/gh_pr1");
    TestCase {
        wdb_path: base.join("repro_0001_record_trailer_arp_tb.wdb"),
        fst_path: base.join("repro_0001_record_trailer_arp_tb.fst"),
        max_mismatches: 30,
    }
    .run();
}

#[test]
fn test_contrib_ip_checksum() {
    let base = PathBuf::from("wdb_files/wdbcvt-waveforms/testdata/contrib/gh_pr1");
    TestCase {
        wdb_path: base.join("repro_0003_partial_first_write_ip_checksum.wdb"),
        fst_path: base.join("repro_0003_partial_first_write_ip_checksum.fst"),
        max_mismatches: 30,
    }
    .run();
}

#[test]
fn test_potato() {
    let base = PathBuf::from("wdb_files/wdbcvt-waveforms/hdl/potato");
    TestCase {
        wdb_path: base.join("sim.wdb"),
        fst_path: base.join("sim.fst"),
        // Large design with many VHDL package scopes not in FST.
        max_mismatches: 50,
    }
    .run();
}

// ---------------------------------------------------------------------------
// Unit tests for internal parsing
// ---------------------------------------------------------------------------

#[test]
fn test_open_simple_vhdl() {
    let wdb =
        WdbFile::open("wdb_files/wdbcvt-waveforms/hdl/corpus/t6_var_int______/sim.wdb")
            .expect("open WDB");
    let hier = wdb.hierarchy();
    let root = hier.root();
    assert_eq!(hier.scope(root).name, "_top");
    assert!(!hier.child_scopes(root).is_empty(), "root should have children");
    assert_eq!(wdb.time_unit().exponent, -12);
}

#[test]
fn test_signal_load_simple() {
    let mut wdb =
        WdbFile::open("wdb_files/wdbcvt-waveforms/hdl/corpus/t6_var_int______/sim.wdb")
            .expect("open WDB");
    wdb.load_all_signals().expect("load signals");

    let hier = wdb.hierarchy();
    let var_ref = hier.find_var("_top.tb.s").expect("find _top.tb.s");
    let sid = hier.var(var_ref).signal_id.expect("tb.s should have signal ID");
    let changes = wdb.signal_changes(sid).expect("should have value changes");
    assert!(!changes.is_empty(), "tb.s should have value changes");
}

#[test]
fn test_selective_signal_load() {
    let mut wdb =
        WdbFile::open("wdb_files/wdbcvt-waveforms/hdl/corpus/t6_var_int______/sim.wdb")
            .expect("open WDB");

    let hier = wdb.hierarchy();
    let s_ref = hier.find_var("_top.tb.s").expect("find _top.tb.s");
    let s_sid = hier.var(s_ref).signal_id.unwrap();
    let v_ref = hier.find_var("_top.tb.p.v").expect("find _top.tb.p.v");
    let v_sid = hier.var(v_ref).signal_id.unwrap();

    // Load only tb.s.
    wdb.load_signals(&[s_sid]).expect("load s");
    assert!(wdb.signal_changes(s_sid).map(|c| !c.is_empty()).unwrap_or(false));
    // tb.p.v should not be loaded yet.
    assert!(wdb.signal_changes(v_sid).is_none());
}

#[test]
fn test_hierarchy_walk() {
    let wdb =
        WdbFile::open("wdb_files/wdbcvt-waveforms/hdl/corpus/t19_v_wor_______/sim.wdb")
            .expect("open WDB");
    let hier = wdb.hierarchy();
    let mut scope_names: Vec<String> = Vec::new();
    hier.walk_scopes(|_, scope| scope_names.push(scope.name.clone()));
    assert!(scope_names.contains(&"_top".to_string()));
    assert!(scope_names.contains(&"tb".to_string()));
}

#[test]
fn test_scopes_in_vars_in() {
    let wdb =
        WdbFile::open("wdb_files/wdbcvt-waveforms/hdl/corpus/t53_inst3_empty_/sim.wdb")
            .expect("open WDB");
    let hier = wdb.hierarchy();

    // scopes_in(None) → top-level scopes (children of _top).
    let top_scopes = hier.scopes_in(None);
    assert!(!top_scopes.is_empty(), "should have top-level scopes");
    let top_names: Vec<&str> = top_scopes.iter().map(|&sr| hier.scope(sr).name.as_str()).collect();
    assert!(top_names.contains(&"tb"), "tb should be a top-level scope");

    // scopes_in(Some(tb)) → children of tb (d0, d1, d2, p).
    let tb_ref = hier.find_scope("_top.tb").expect("find tb");
    let tb_children = hier.scopes_in(Some(tb_ref));
    assert!(tb_children.len() >= 3, "tb should have at least d0, d1, d2");

    // vars_in(Some(tb)) → tb.s
    let tb_vars = hier.vars_in(Some(tb_ref));
    let tb_var_names: Vec<&str> = tb_vars.iter().map(|&vr| hier.var(vr).name.as_str()).collect();
    assert!(tb_var_names.contains(&"s"), "tb should have signal s");
}

#[test]
fn test_type_table_parsed() {
    let wdb =
        WdbFile::open("wdb_files/wdbcvt-waveforms/hdl/corpus/t6_var_int______/sim.wdb")
            .expect("open WDB");
    assert!(!wdb.hierarchy().types.is_empty(), "type table should not be empty");
}

#[test]
fn test_var_by_signal_id_roundtrip() {
    let wdb =
        WdbFile::open("wdb_files/wdbcvt-waveforms/hdl/corpus/t6_var_int______/sim.wdb")
            .expect("open WDB");
    let hier = wdb.hierarchy();
    let vr = hier.find_var("_top.tb.s").unwrap();
    let sid = hier.var(vr).signal_id.unwrap();
    let found = hier.var_by_signal_id(sid).expect("reverse lookup should work");
    assert_eq!(found, vr);
}
